{
 "title": "Dados de rede conforme URL",
 "description": "RTT, Latência e HTTPStatus conforme URL",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_url",
    "label": "HostUrl",
    "query": "\"google.com\",\"rnp.br\",\"youtube.com\""
   }
  ]
 },
 "panels": [
  {
   "title": "Historico de Latência",
   "type": "timeseries",
   "description": "histórico de latência do host",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"network_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ping_latency_ms\")\r\n  |> filter(fn: (r) =>  if (${host_url} != \"All\") then (r.host == ${host_url}) else true )"
    }
   ]
  },
  {
   "title": "Status Http dos Hosts",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"network_metrics\" and\r\n      r._field == \"http_status_code\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      r with http_status:\r\n        if r._value == 200 then \"OK\"\r\n        else if r._value == 301 then \"REDIRECT\"\r\n        else if r._value == 404 then \"NOT FOUND\"\r\n        else if r._value >= 500 then \"SERVER ERROR\"\r\n        else \"UNKNOWN\"\r\n  }))\r\n  |> keep(columns: [\"_time\", \"http_status\", \"host\"])"
    }
   ]
  },
  {
   "title": "Historico de Delay de Resposta",
   "type": "timeseries",
   "description": "histórico de delay de resposta do host",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"network_metrics\")\r\n  |> filter(fn: (r) => r._field == \"http_response_time_ms\")\r\n  |> filter(fn: (r) =>  if (${host_url} != \"All\") then (r.host == ${host_url}) else true )"
    }
   ]
  }
 ]
}